name: NotQuests
version: '${version}'
main: rocks.gravili.notquests.NotQuests
api-version: 1.17
authors: [ NoeX ]
description: Flexible, open, GUI Quest Plugin for Minecraft 1.17 and 1.18
website: quests.notnot.pro
softdepend:
  - ProtocolLib #For packetevents?
  - ProtocolSupport #For packetevents?
  - ViaVersion #For packetevents?
  - Geyser-Spigot #For packetevents?
  - Citizens
  - Vault
  - PlaceholderAPI
  - MythicMobs
  - EliteMobs
  - BetonQuest
  - WorldEdit
  - Slimefun
  - LuckPerms
  - UltimateClans
  - Towny
  - Jobs
  - ProjectKorra
load: POSTWORLD
permissions:
  notquests.admin:
    default: op
    description: Gives the player permission to everything in the plugin.
    children:
      notquests.admin.armorstandeditingitems: true
      notquests.use: true
  notquests.admin.armorstandeditingitems:
    default: op
    description: Gives the player permission to use quest editing items for armor stands.
  notquests.use:
    default: true
    description: Gives the player permission to use the /notquests user command. They can not create new quests or other administrative tasks with just this permission.